from __future__ import annotations

from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[1]


def assert_contains_all(path: Path, phrases: list[str]) -> None:
    assert path.exists()
    text = path.read_text(encoding="utf-8")

    for phrase in phrases:
        assert phrase in text


@pytest.mark.parametrize(
    ("relative_path", "phrases"),
    [
        (
            "docs/phase2.md",
            [
                "Phase 2 is closed",
                "fail_closed_non_autonomous",
                "autonomous_allowed = False",
                "safe_pass_enabled = False",
                "StateMachine",
                "Scheduler",
                "TaskCommitter",
                "SupervisorMonitor",
                "manual no-op execution harness",
                "manual no-op staging",
                "manual scheduler-dispatched no-op cycle",
                "execution_readiness.ready becomes True",
                "task_lifecycle_audit passes",
                "task_execution_audit passes",
                "supervisor_health_check reports supervisor_health_ok",
                "verify_foundation reports foundation_passed: True",
                "pytest tests -v passes",
                "automatic scheduler-to-executor integration",
                "persistent scheduler loop",
                "autonomous operation",
                "safe-pass enablement",
                "model profile promotion",
                "real Ollama chat/generate calls",
                "cloud provider calls",
                "real NetworkGateway fetches",
                "real SandboxGateway process execution",
                "real MemoryGateway embedding writes/query",
                "Telegram operator control plane",
                "agent layer",
                '"executor": "noop_task_executor"',
                '"executed": true',
                '"side_effects": "none"',
                '"tools_used": []',
                '"model_calls": []',
                '"network_calls": []',
                '"sandbox_calls": []',
            ],
        ),
        (
            "docs/phase3.md",
            [
                "Phase 3 is closed",
                "fail_closed_non_autonomous",
                "autonomous_allowed = False",
                "safe_pass_enabled = False",
                "ManifestBinder JSON Schema validation",
                "ManifestBinder SHA256 verification",
                "ManifestBinder semantic validation",
                "ManifestBinder tool ID map validation",
                "ManifestBinder effective-capability derivation",
                "PolicyEngine seven-step tool authorization",
                "PlanInjectionScanner deterministic checks",
                "PlanInjectionScanner classifier-safe-pass path",
                "PlanInjectionScanner explicit return contract",
                "active_policy_manifest_rows_match_payload_identity",
                "standard tool source paths",
                "standard tool additional_checks",
                "checked_count: 15",
                "violation_count: 0",
                "369 passed",
                r"python -m py_compile axiom\core\policy_security_audit.py",
                r"pytest tests\test_manifest_binder.py tests\test_policy_engine.py",
                "pytest tests -v",
                r"python tools\verify_foundation.py",
                r"python tools\audit_task_lifecycle.py",
                r"python tools\audit_task_execution.py",
                r"python tools\audit_policy_security.py",
                "autonomous operation",
                "safe-pass enablement",
                "model profile promotion",
                "classifier calibration approval",
                "real Ollama /api/chat or /api/generate calls",
                "real cloud model/provider calls",
                "real NetworkGateway fetches",
                "real SandboxGateway process execution",
                "real MemoryGateway embedding writes/query",
                "Telegram/operator control plane",
                "agent layer",
                "persistent scheduler service",
                "automatic scheduler-to-executor integration",
                "terminal shortcuts that mutate runtime state directly",
                "No Phase 3 implementation item remains before Phase 4",
                "Phase 4 must not begin until Jeremy explicitly authorizes",
                "ModelGateway cloud cascade requires provider/config approval",
                "MemoryGateway work must preserve sqlite-vec batch and database invariants",
                "NetworkGateway work requires Brave/free-tier approval before real fetches",
                "SandboxGateway work requires Windows Job Object specifics before real execution",
                "No real model, cloud, network, sandbox, memory, Telegram, agent, or scheduler authority is enabled by this closeout",
                "Phase 3 is active",
                "axiom/core/policy_security_audit.py",
                "tools/audit_policy_security.py",
                "tests/test_policy_security_audit.py",
                "tool_capability_map_semantic_contracts",
                "active_policy_manifests_validate_schema_and_policy",
                "manifest row-to-payload identity",
                "standard tool source paths match expected policy objects",
                "standard tool additional_checks match expected enforcement checks",
                "standard tools do not declare operator-control command bindings",
                "session_controller tools bind one schema-valid operator command each",
                "role_manifests_do_not_declare_operator_control_commands",
                "operator_control_manifests_bind_single_command",
                "plan_injection_scanner_return_contract_is_stable",
                "security_events_table_supports_audit_coverage",
                r"python -m py_compile axiom\core\policy_security_audit.py tests\test_policy_security_audit.py",
                r"pytest tests\test_policy_security_audit.py -v",
                r"python tools\supervisor_health_check.py <SESSION_ID>",
                "Do not type angle brackets literally",
                "Telegram/operator control execution",
                "register_manifests.py automatic execution",
            ],
        ),
        (
            "docs/phase4.md",
            [
                "Phase 4 is closed",
                "fail_closed_non_autonomous",
                "autonomous_allowed = False",
                "safe_pass_enabled = False",
                "does not authorize autonomous operation",
                "does not authorize autonomous operation, safe-pass enablement, agent execution, Telegram/operator control execution, or scheduler-to-executor automation",
                "ModelGateway cloud cascade readiness validation",
                "ModelGateway bounded cloud cascade HTTP execution",
                "MemoryGateway sqlite-vec invariant hardening",
                "MemoryGateway real write/query readiness",
                "MemoryGateway local Ollama /api/embed embedding provider adapter",
                "NetworkGateway Brave Search readiness and execution",
                "SandboxGateway Windows Job Object execution boundary",
                "Operator command index v10 gateway smoke registration",
                "cloud model calls require real_calls_enabled and --live smoke intent",
                "Brave Search fetches require real_fetch_enabled and --live smoke intent",
                "Windows Job Object execution requires real_execution_enabled and --live smoke intent",
                "MemoryGateway write/query requires real_operations_enabled",
                "groq -> llama-3.3-70b-versatile -> AXIOM_GROQ_SMOKE_OK",
                "cerebras -> gpt-oss-120b -> AXIOM_CEREBRAS_SMOKE_OK",
                "sambanova -> Meta-Llama-3.3-70B-Instruct -> AXIOM_SAMBANOVA_SMOKE_OK",
                "openrouter -> openrouter/auto -> AXIOM_OPENROUTER_SMOKE_OK",
                "full cloud cascade -> groq primary -> AXIOM_CLOUD_CASCADE_SMOKE_OK",
                "brave_search -> status 200 -> response_bytes 14152",
                "windows_job_object -> cmd.exe /c exit 0 -> exit_code 0",
                "ollama_embed -> nomic-embed-text -> AXIOM_MEMORY_SMOKE_OK",
                "NetworkGateway Brave Search: session_id 4587, task_id 3910",
                "SandboxGateway Windows Job Object: session_id 4591, task_id 3914",
                "MemoryGateway Ollama embedding: session_id 4592, task_id 3915",
                "pytest tests -v",
                "467 passed",
                r"python tools\memory_gateway_smoke_test.py --live --json",
                "query_contains_sentinel: true",
                r"python tools\verify_foundation.py",
                r"python tools\audit_task_lifecycle.py",
                r"python tools\audit_task_execution.py",
                r"python tools\audit_policy_security.py",
                "policy_security_audit passed",
                "checked_count: 15",
                "violation_count: 0",
                "tests\\test_phase4_closeout_doc.py",
                "autonomous operation",
                "safe-pass enablement",
                "model profile promotion",
                "classifier calibration approval",
                "real Ollama /api/chat or /api/generate calls",
                "cloud model calls outside the approved ModelGateway cloud cascade",
                "network fetches outside the approved Brave Search NetworkGateway wrapper",
                "sandbox execution outside the approved Windows Job Object SandboxGateway wrapper",
                "MemoryGateway embedding writes/query outside approved real-operation gates",
                "Telegram/operator control plane",
                "agent layer",
                "persistent scheduler service",
                "automatic scheduler-to-executor integration",
                "unbounded provider, network, sandbox, or memory execution",
                "Jeremy explicitly authorizes Phase 5",
                "Phase 5 objective and bounded first slice are named",
                "Phase 5 authority expansion, if any, is stated explicitly",
                "any new provider, agent, scheduler, Telegram, or autonomous surface has a written gate",
                "rollback and smoke-test commands are identified before implementation",
                "existing Phase 4 smoke wrappers remain dry-run by default",
                "standard audits pass before and after the first Phase 5 slice",
                "No Phase 4 implementation item remains before Phase 5",
                "Phase 5 must not begin until Jeremy explicitly authorizes the next bounded slice and its prerequisites",
                "Phase 4 is authorized for bounded implementation",
                "ModelGateway cloud-cascade readiness validation",
                "ModelGateway cloud-cascade HTTP execution",
                "ModelGateway operator-facing cloud cascade smoke wrapper/reporting",
                "MemoryGateway write/query readiness",
                "MemoryGateway local Ollama `/api/embed` provider adapter",
                "operator smoke wrapper behind explicit `--live`",
                "NetworkGateway Brave Search readiness/execution",
                "SandboxGateway Windows Job Object readiness/execution",
                "API keys are read only from configured environment variable names",
                "They are never written to provider_usage, resource_usage, or test output",
                "The test suite uses injected HTTP transports",
                "does not make real cloud requests",
                "does not call a live embedding model or external embedding API",
                "does not perform real local Ollama `/api/chat` or `/api/generate` calls",
                "provider_configuration_approved must be true",
                "approved_by_panel_version must be present when approved",
                "provider_order must contain known cloud providers only",
                "provider_order must not contain duplicates",
                "providers must contain known cloud providers only",
                "providers must not contain duplicates",
                "enabled providers must declare a model",
                "enabled providers must declare an API key environment variable name",
                "provider endpoint URLs must use https",
                "provider timeout seconds must be positive",
                "cerebras",
                "groq",
                "openrouter",
                "sambanova",
                "CloudCascadeNotApprovedError",
                "ModelGatewayDisabledError",
                "real_calls_enabled",
                "CloudCredentialsError",
                "provider HTTP failures record terminal provider_usage status and continue failover",
                "invalid provider responses record failed provider_usage status",
                "CloudModelResponse.response_text",
                "https://api.cerebras.ai/v1/chat/completions",
                "https://api.groq.com/openai/v1/chat/completions",
                "https://openrouter.ai/api/v1/chat/completions",
                "https://api.sambanova.ai/v1/chat/completions",
                "memory_items table must exist",
                "memory_item_embeddings sqlite-vec table must exist",
                "memory_item_embeddings must use vec0",
                "memory_item_embeddings.embedding must be float[768]",
                "memory_items.embedding_dim must default to 768",
                "memory_items.embedding_dim must CHECK embedding_dim = 768",
                "idx_memory_items_content_model must be a unique index",
                "idx_memory_items_content_model must cover content_sha256 and embedding_model",
                "sqlite-vec batches remain capped at 100 vectors",
                "require_invariants raises MemoryGatewayError when invariants drift",
                "query_disabled still raises MemoryGatewayDisabledError",
                "write_disabled still raises MemoryGatewayDisabledError",
                "write requires MemoryGatewayConfig.real_operations_enabled",
                "write/query require embedding_provider_approved",
                "write/query require approved_by_panel_version",
                "write/query require an injected embedding provider",
                "write/query require manifest authorization metadata",
                "write requires memory write authorization",
                "write requires write_requires_dedupe",
                "query requires memory read authorization",
                "query enforces max_query_results",
                "hashes content with SHA256 before insert",
                "dedupes by content_sha256 and embedding_model",
                "inserts memory_items rows as pending before vector insert",
                "inserts memory_item_embeddings rows with rowid equal to memory_item_id",
                "updates embedding_status to indexed after vector insert",
                "queries sqlite-vec with MATCH and k",
                "returns indexed memory_items ordered by sqlite-vec distance",
                "MemoryGateway operator-facing local Ollama smoke wrapper/reporting",
                "provider: ollama_embed",
                "host: http://localhost:11434",
                "endpoint: /api/embed",
                "model: nomic-embed-text",
                "embedding_dim: 768",
                "Ollama host must use http",
                "Ollama host must be localhost, 127.0.0.1, or ::1",
                "Ollama port must be 11434",
                "Ollama endpoint path must be /api/embed",
                "Ollama response must include an embeddings list",
                "Ollama embeddings must match embedding_dim 768",
                "real local Ollama embedding calls require MemoryGateway real-operation gates",
                "real local Ollama embedding calls require operator smoke --live",
                "vector values are not printed by the operator smoke wrapper",
                "does not call `/api/chat` or `/api/generate`",
                r"python tools\memory_gateway_smoke_test.py",
                r"python tools\memory_gateway_smoke_test.py --live",
                "Real local Ollama `/api/embed` write/query calls require `--live`",
                "Live local Ollama embedding smoke completed",
                "endpoint: http://localhost:11434/api/embed",
                "session_id: 4592",
                "task_id: 3915",
                "write_status: indexed",
                "query_result_count: 1",
                "fake HTTP transports",
                "NetworkGateway Brave Search readiness and execution",
                "brave_search",
                "endpoint: https://api.search.brave.com/res/v1/web/search",
                "api key env var: BRAVE_SEARCH_API_KEY",
                "header: X-Subscription-Token",
                "official Brave Search API documentation and pricing surface",
                "monthly free credits and 50 requests per second capacity",
                "fetch_disabled still raises NetworkAccessDeniedError",
                "real Brave fetch requires NetworkGatewayConfig.real_fetch_enabled",
                "real Brave fetch requires provider_configuration_approved",
                "real Brave fetch requires approved_by_panel_version",
                "real Brave fetch requires BRAVE_SEARCH_API_KEY",
                "provider endpoint must use https",
                "provider endpoint host must be api.search.brave.com",
                "provider endpoint path must be /res/v1/web/search",
                "network policy must be allowlist_only",
                "allowlist must include api.search.brave.com",
                "redirect_policy must be deny",
                "Brave count must be between 1 and 20",
                "response bytes are recorded before success or failure",
                "API key values are not written to resource_usage or smoke output",
                r"python tools\network_gateway_smoke_test.py",
                r"python tools\network_gateway_smoke_test.py --live",
                "Real Brave Search network calls require `--live`",
                "windows_job_object",
                "max_ram_mb: 256",
                "max_wall_clock_seconds: 60",
                "network_access: denied",
                "kill_on_job_close: true",
                "active_process_limit: 1",
                "execute_disabled still raises SandboxExecutionDeniedError",
                "real sandbox execution requires SandboxGatewayConfig.real_execution_enabled",
                "real sandbox execution requires windows_job_object_approved",
                "real sandbox execution requires approved_by_panel_version",
                "real sandbox execution requires manifest authorization metadata",
                "real sandbox execution requires allow_execute",
                "max_ram_mb cannot exceed 256",
                "max_wall_clock_seconds cannot exceed 60",
                "network_access must remain denied",
                "active_process_limit must remain 1",
                "kill_on_job_close must remain enabled",
                "process is created suspended before Job Object assignment",
                "Job Object sets process memory and job memory caps",
                "Job Object enforces active process limit 1",
                "wall-clock timeout terminates the Job Object",
                "RAM and wall-clock usage are recorded before success or failure",
                r"python tools\sandbox_gateway_smoke_test.py",
                r"python tools\sandbox_gateway_smoke_test.py --live",
                "Real sandbox process execution requires `--live`",
                "Live smoke tests completed",
                "full cascade -> groq primary -> AXIOM_CLOUD_CASCADE_SMOKE_OK",
                "Validated live cascade order",
                "cerebras max_tokens: 96",
                "openrouter max_tokens: 256",
                r"python tools\cloud_cascade_smoke_test.py --target cascade",
                r"python tools\cloud_cascade_smoke_test.py --target cascade --live",
                "Real cloud model calls require `--live`",
                r"python -m py_compile axiom\gateways\model_gateway.py axiom\gateways\memory_gateway.py axiom\gateways\network_gateway.py axiom\gateways\sandbox_gateway.py",
                r"pytest tests\test_model_gateway_wrapper.py tests\test_memory_gateway.py tests\test_network_gateway.py tests\test_sandbox_gateway.py",
                r"python tools\memory_gateway_smoke_test.py --json",
                "unauthorized real cloud model/provider calls outside ModelGateway cloud cascade",
                "ungated real NetworkGateway fetches outside approved Brave Search wrapper",
                "ungated real SandboxGateway process execution outside approved Windows Job Object wrapper",
                "ungated live MemoryGateway embedding-provider calls",
                "Remaining Phase 4 implementation is:",
                "none",
                r"docs\phase4.md",
            ],
        ),
        (
            "docs/phase5.md",
            [
                "Phase 5 agent foundations are manual-only and manifest-bound",
                "tools/execute_goal_planning_task.py",
                "tools/execute_task_planning_task.py",
                "tools/execute_tool_execution_task.py",
                "tools/execute_result_verification_task.py",
                "tools/run_manual_agent_foundation_smoke.py",
                "autonomous operation",
                "safe-pass enablement",
                "scheduler-to-agent automation",
                "Telegram/operator control plane",
                "task creation by agents",
                "real model calls",
                "cloud cascade calls",
                "network fetches",
                "sandbox execution",
                "memory reads or writes",
                "filesystem reads or writes",
                "new artifact schema creation",
                "Phase 5 agent foundation is implemented",
                "fail_closed_non_autonomous",
                "autonomous_allowed = False",
                "safe_pass_enabled = False",
                "GoalPlanner manifest-bound executor",
                "TaskPlanner manifest-bound executor",
                "ToolExecutor manifest-bound planning-only executor",
                "ResultVerifier manifest-bound summary-only executor",
                "manual agent foundation smoke path",
                "read-only agent boundary audit",
                "python tools/register_manifests.py",
                "tests\\test_phase5_agent_cli.py",
                "tests\\test_phase5_docs.py",
                "tests\\test_agent_boundary_audit.py",
                "python tools\\verify_foundation.py",
                "python tools\\audit_task_lifecycle.py",
                "python tools\\audit_task_execution.py",
                "python tools\\audit_policy_security.py",
                "python tools\\audit_agent_boundary.py",
                "pytest tests -v",
            ],
        ),
        (
            "docs/phase6.md",
            [
                "Slices 6A through 6I are implemented",
                "Build the operator control plane foundation",
                "6A. Entry Gate And Scope Lock",
                "6B. Operator Command Manifest Set",
                "6C. Local Operator Command Parser",
                "6D. Operator Command Ledger",
                "6E. Terminal Operator Control Visibility",
                "6F. External Adapter Design Packet",
                "6G. Telegram Gateway Runtime Foundation",
                "python tools\\audit_agent_boundary.py",
                "Phase 6A is the authorized entry-gate slice",
                "Jeremy explicitly authorizes the bounded slice",
                "Phase 5 agent boundary audit passes",
                "The proposed slice does not enable autonomous operation",
                "The proposed slice does not connect external chat or Telegram runtime",
                "autonomous operation",
                "safe-pass enablement",
                "scheduler-to-agent automation",
                "scheduler-to-executor automation",
                "real model calls",
                "cloud cascade calls",
                "network fetches",
                "sandbox execution",
                "memory writes",
                "Telegram bot runtime",
                "external command ingestion",
                "agent task creation",
                "child task commits",
                "operator command execution from external adapters",
                "read_only_status",
                "read_only_audit",
                "read_only_queue_inspection",
                "read_only_task_inspection",
                "local_intent_record",
                "local_intent_reject",
                "local_intent_authorization_marker",
                "design_only_external_adapter",
                "autonomous_enablement",
                "safe_pass_enablement",
                "model_profile_promotion",
                "gateway_runtime_call",
                "network_runtime_call",
                "sandbox_runtime_call",
                "memory_write_runtime_call",
                "scheduler_start",
                "agent_execution",
                "external_command_execution",
                "remove docs\\phase6.md",
                "remove Phase 6A references from docs\\phase6.md",
                "remove phase6 from ui\\terminal\\modules\\52-docs.ps1",
                "python tools\\verify_foundation.py",
                "python tools\\audit_task_lifecycle.py",
                "python tools\\audit_task_execution.py",
                "python tools\\audit_policy_security.py",
                "python tools\\audit_agent_boundary.py",
                "pytest tests\\test_phase6_entry_gate_doc.py -v",
                "docs\\phase6.md",
            ],
        ),
        (
            "docs/phase8.md",
            [
                "Phase 8A is a release-freeze/documentation-reconciliation slice.",
                "Phase 7 E2E readiness/passing is now recorded.",
                "acceptance_inventory_passed = true",
                "e2e_ready = true",
                "e2e_blockers = []",
                "final mapped acceptance run: 130 passed in 23.08s",
                "approved live classifier calibration run present",
                "current model fingerprint tied to approved calibration present",
                "safe-pass readiness enabled in latest session",
                "explicit operator approval material supplied",
                "safe-pass readiness may be enabled for the bounded Phase 7 E2E path",
                "autonomous_operation_enabled remains false / 0",
                "scheduler-to-agent automation remains unauthorized",
                "scheduler-to-executor automation remains unauthorized",
                "live Telegram polling remains explicit/manual and not a default service",
                "terminal surfaces remain read-only unless backed by approved tools",
                "No feature work belongs in Phase 8A.",
                "Telegram polling startup or registration",
                "gateway authority changes",
                "Set-Location C:\\axiom",
                ".\\venv\\Scripts\\Activate.ps1",
                "axiom-preflight",
                "axiom-phase7",
                "python tools\\run_phase7_acceptance.py --json",
                "python tools\\run_phase7_acceptance.py --run --include-e2e --operator-approved-e2e",
                "python tools\\audit_phase6_closeout.py",
                "python tools\\audit_agent_boundary.py",
                "python tools\\audit_telegram_gateway.py",
                "pytest tests -v",
                "no runtime feature work is included",
                "Any later runtime expansion requires a separately approved phase",
                "Phase 8B is audit/planning only.",
                "This audit does not rename files, delete files, move files",
                "enable autonomy",
                "add Telegram default runtime",
                "add scheduler-to-agent automation",
                "add scheduler-to-executor automation",
                "expand gateway authority",
                "Phase 8A boundaries remain intact.",
                "axiom\\agents\\_init_.py",
                "axiom\\agents\\__init__.py",
                "inspect_*.py",
                "Set-Location",
                "orColor...#A8FF60...,",
                "package-lock.json",
                "project_state_snapshot_2026-05-24T20-45-36Z.json",
                "Tracked `venv\\` paths",
                "Tracked `logs\\` handoff/snapshot paths",
                "Governance archive/deprecated paths",
                "git ls-files --deleted",
                "git ls-files --ignored --others --exclude-standard",
                "rg \"<candidate-name-or-symbol>\"",
                "Python imports",
                "Terminal command or registry rename",
                "Generated handoff/snapshot references must be classified separately",
                "python -m pytest tests -k \"phase8 or docs or terminal\" -v",
            ],
        ),
    ],
)
def test_historical_docs_record_required_text(relative_path: str, phrases: list[str]) -> None:
    assert_contains_all(ROOT / relative_path, phrases)


def test_historical_docs_terminal_docs_index_includes_phase6() -> None:
    docs_module = ROOT / "ui" / "terminal" / "modules" / "52-docs.ps1"
    assert_contains_all(docs_module, ["phase6", "docs\\phase6.md"])
